apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: link-parser
  name: linkparser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link-parser
  template:
    metadata:
      labels:
        app: link-parser
    spec:
      containers:
      - image: ghcr.io/tyrwhitt/linkparser:IMAGE_TAG
        name: linkparser
        args:
        - --create-readinessprobe-file
        - -o
        - json
        - -u
        - https://yle.fi
        - -u
        - https://sellan.eu
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/linkparser-started
          initialDelaySeconds: 5
          periodSeconds: 5
