name: Build docker image

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Debug
      run: env | sort

    - name: Login to ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    #Hard coded namespace in image name, since my username has capital T. Some workaround ideas https://github.com/orgs/community/discussions/25768
    - name: Docker build
      run: |
        docker build  -f Dockerfile -t ghcr.io/tyrwhitt/linkparser:$(git rev-parse --short HEAD) .
        docker push ghcr.io/tyrwhitt/linkparser:$(git rev-parse --short HEAD)
